require: rubocop-performance

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4


### METRICS ###

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'test/*' # Rantly syntax

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 180


### STYLE ###

# Rantly syntax
Style/MultilineBlockChain:
  Exclude:
    - 'examples/***/**/*'
    - 'test/*'

Style/NumericPredicate:
  Exclude:
    - 'lib/rantly/shrinks.rb' # TODO: Use infinite range with case in Ruby 2.6
