# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rantly 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rantly"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Howard Yeh", "Anthony Bargnesi", "Eric Bischoff"]
  s.date = "2015-12-14"
  s.email = ["hayeah@gmail.com", "abargnesi@gmail.com", "ebischoff@nerim.net"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION.yml",
    "lib/rantly.rb",
    "lib/rantly/data.rb",
    "lib/rantly/generator.rb",
    "lib/rantly/minitest.rb",
    "lib/rantly/minitest_extensions.rb",
    "lib/rantly/property.rb",
    "lib/rantly/rspec.rb",
    "lib/rantly/rspec_extensions.rb",
    "lib/rantly/shrinks.rb",
    "lib/rantly/silly.rb",
    "lib/rantly/spec.rb",
    "lib/rantly/testunit_extensions.rb",
    "rantly.gemspec",
    "test/rantly_test.rb",
    "test/shrinks_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "https://github.com/abargnesi/rantly"
  s.rubygems_version = "2.4.5.1"
  s.summary = "Ruby Imperative Random Data Generator and Quickcheck"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>, ["~> 5.7.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
    else
      s.add_dependency(%q<minitest>, ["~> 5.7.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
    end
  else
    s.add_dependency(%q<minitest>, ["~> 5.7.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
  end
end

